# Generated by Django 4.1.5 on 2023-02-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='brand',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='DOB',
            new_name='Brith',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='licenseNum',
            new_name='Color',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='model',
            new_name='LicenseNum',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='plateNum',
            new_name='Model',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='special_info',
            new_name='PlateNum',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='max_pnum',
            new_name='maxP',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='cardInfo',
        ),
        migrations.AddField(
            model_name='driver',
            name='Special',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
