# Generated by Django 4.1.5 on 2023-02-03 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_rename_brand_driver_brand_rename_dob_driver_brith_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('OwnerEmail', models.CharField(default='kh492@duke.edu', max_length=200)),
                ('driver', models.CharField(blank=True, max_length=200, null=True)),
                ('sharable', models.BooleanField(blank=True, default=False, null=True)),
                ('RemainSeats', models.IntegerField(default=0)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Vtype', models.CharField(default='Sedan', max_length=20)),
                ('Special', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=20)),
                ('party_size', models.IntegerField(default=1)),
                ('ride_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ridedetail')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
